apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-immediate
  resources:
    requests:
      storage: 4Gi
