executor: KubernetesExecutor

images:
  airflow:
    repository: apache/airflow
    tag: 2.9.1-python3.11
    pullPolicy: IfNotPresent

dags:
  gitSync:
    enabled: true
    repo: https://github.com/kalebeasilvadev/airflow-project.git
    branch: main
    subPath: dags
    depth: 1

airflow:
  config:
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
    AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: apache/airflow
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: 2.9.1-python3.11

  extraPipPackages: |
    apache-airflow-providers-postgres
    pandas
    requests

logs:
  persistence:
    enabled: true

postgresql:
  primary:
    persistence:
      enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

webserver:
  defaultUser:
    enabled: true
    username: admin
    password: admin
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  nodeSelector:
    kubernetes.io/hostname: airflow

scheduler:
  nodeSelector:
    kubernetes.io/hostname: airflow
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

triggerer:
  nodeSelector:
    kubernetes.io/hostname: airflow
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

worker:
  nodeSelector:
    kubernetes.io/hostname: airflow
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 600m
      memory: 1Gi
