executor: KubernetesExecutor

images:
  airflow:
    repository: apache/airflow
    tag: 2.9.1-python3.11
    pullPolicy: IfNotPresent

dags:
  gitSync:
    enabled: true
    repo: https://github.com/kalebeasilvadev/airflow-project.git
    branch: main
    subPath: dags
    depth: 1

airflow:
  config:
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
    AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: apache/airflow
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: 2.9.1-python3.11

  extraPipPackages: |
    apache-airflow-providers-google
    apache-airflow-providers-amazon
    apache-airflow-providers-postgres
    apache-airflow-providers-http
    pandas
    requests

logs:
  persistence:
    enabled: false

postgresql:
  primary:
    persistence:
      enabled: false

webserver:
  defaultUser:
    enabled: true
    username: admin
    password: admin  # Altere para segredo via Secret em produção
