executor: KubernetesExecutor

images:
  airflow:
    repository: apache/airflow
    tag: 2.9.1-python3.11
    pullPolicy: IfNotPresent

dags:
  gitSync:
    enabled: true
    repo: https://github.com/kalebeasilvadev/airflow-project.git
    branch: main
    subPath: dags
    depth: 1

airflow:
  config:
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
    AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: apache/airflow
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: 2.9.1-python3.11

  extraPipPackages: |
    apache-airflow-providers-postgres
    pandas
    requests

postgresql:
  primary:
    persistence:
      enabled: true
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    containerSecurityContext:
      runAsUser: 1001
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    # ⚠️ Impede que o PostgreSQL veja todos os CPUs
    extraFlags:
      - "--cpu=0.5"

    # 🔽 alternativo: usar cpulimit na entrada (gambiarra mais forte)
    extraEnvVars:
      - name: PG_CPU_LIMIT
        value: "0.5"



webserver:
  defaultUser:
    enabled: true
    username: admin
    password: admin
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  nodeSelector:
    kubernetes.io/hostname: airflow

scheduler:
  nodeSelector:
    kubernetes.io/hostname: airflow
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

triggerer:
  nodeSelector:
    kubernetes.io/hostname: airflow
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

workers:  # <- nome correto aqui!
  nodeSelector:
    kubernetes.io/hostname: airflow
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 600m
      memory: 1Gi
