executor: KubernetesExecutor

images:
  airflow:
    repository: apache/airflow
    tag: 2.10.5
    pullPolicy: IfNotPresent

dags:
  gitSync:
    enabled: true
    repo: https://github.com/kalebeasilvadev/airflow-project.git
    branch: main
    depth: 1
    subPath: dags
    wait: 15


airflow:
  config:
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
    AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: apache/airflow
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: 2.10.5
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags/repo/dags

  extraPipPackages: |
    apache-airflow-providers-postgres
    pandas
    requests

postgresql:
  primary:
    persistence:
      enabled: true
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
    containerSecurityContext:
      runAsUser: 1001
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

webserver:
  defaultUser:
    enabled: true
    username: admin
    password: admin
  nodeSelector:
    kubernetes.io/hostname: airflow
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1.5Gi

scheduler:
  nodeSelector:
    kubernetes.io/hostname: airflow
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

triggerer:
  nodeSelector:
    kubernetes.io/hostname: airflow
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

workers:
  nodeSelector:
    kubernetes.io/hostname: airflow
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

ingress:
  enabled: true
  web:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    ingressClassName: traefik
    tls:
      enabled: false

logs:
  persistence:
    enabled: true
    existingClaim: airflow-logs





