executor: KubernetesExecutor

images:
  airflow:
    repository: apache/airflow
    tag: 2.9.1-python3.11
    pullPolicy: IfNotPresent

dags:
  gitSync:
    enabled: true
    repo: https://github.com/kalebeasilvadev/airflow-project.git
    branch: main
    subPath: dags
    depth: 1

airflow:
  config:
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
    AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: apache/airflow
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: 2.9.1-python3.11

  extraPipPackages: |
    apache-airflow-providers-postgres
    pandas
    requests

logs:
  persistence:
    enabled: true

postgresql:
  primary:
    persistence:
      enabled: true

webserver:
  defaultUser:
    enabled: true
    username: admin
    password: admin  # Altere para segredo via Secret em produção

# 🔽 Node selector aplicado a todos os componentes
nodeSelector:
  kubernetes.io/hostname: airflow

# 🔽 Se quiser aplicar por componente individual:
 webserver:
   nodeSelector:
     kubernetes.io/hostname: airflow
 scheduler:
   nodeSelector:
     kubernetes.io/hostname: airflow
 triggerer:
   nodeSelector:
     kubernetes.io/hostname: airflow
 worker:
   nodeSelector:
     kubernetes.io/hostname: airflow
